export default [
  { icon: 'fas fa-flag', title: 'Pages', id: 'pages', updates: 6, class: 'text-orange-500' },
  { icon: 'fas fa-heart', title: 'COVID-19 Information Center', id: 'covid', updates: 0, class: 'text-pink-500' },
  { icon: 'fas fa-users', title: 'Friends', id: 'friends', updates: 0 , class: 'text-blue-700'},
  { icon: 'fas fa-users', title: 'Groups', id: 'groups', updates: 2, class: 'text-blue-500' },
  { icon: 'fas fa-bullhorn', title: 'Ad Center', id: 'ad', updates: 0, class: 'text-gray-800' },
  { icon: 'fas fa-chart-bar', title: 'Ads Manager', id: 'ads', updates: 0, class: 'text-blue-400' },
  { icon: 'fas fa-chart-pie', title: 'Business Manager', id: 'bus', updates: 0, class: 'text-yellow-500' },
  { icon: 'fas fa-exclamation-triangle', title: 'Crisis Response', id: 'crisis', updates: 0, class: 'text-green-400' },
  { icon: 'fas fa-calendar', title: 'Events', id: 'events', updates: 0, class: 'text-red-500' },
  { icon: 'fas fa-credit-card', title: 'Facebook Pay', id: 'pay', updates: 0 },
  { icon: 'fas fa-star', title: 'Favourites', id: 'fav', updates: 0, class: 'text-yellow-400' },
  { icon: 'fas fa-user', title: 'Friend lists', id: 'flist', updates: 0, class: 'text-blue-500' },
  { icon: 'far fa-heart', title: 'Fundraisers', id: 'fund', updates: 0, class: 'text-red-500' },
  { icon: 'fab fa-fantasy-flight-games', title: 'Gaming', id: 'gaming', updates: 0, class: 'text-blue-00' },
  { icon: 'fas fa-suitcase', title: 'Jobs', id: 'jobs', updates: 0, class: 'text-orange-700' },
  { icon: 'fas fa-play-circle', title: 'Live videos', id: 'live', updates: 0, class: 'text-red-600' },
  { icon: 'fas fa-clock', title: 'Memories', id: 'memories', updates: 0, class: 'text-blue-500' },
  { icon: 'fab fa-facebook-messenger', title: 'Messenger', id: 'messenger', updates: 0, class: 'text-blue-700' },
  { icon: 'fab fa-facebook-messenger', title: 'Messenger Kids', id: 'kids', updates: 0, class: 'text-green-500' },
  { icon: 'fas fa-calendar', title: 'Most Recent', id: 'recents', updates: 0, class: 'text-orange-500' },
  { icon: 'fas fa-hand-holding-usd', title: 'Offers', id: 'offers', updates: 0, class: 'text-orange-800' },
  { icon: 'fas fa-desktop', title: 'Recent ad activity', id: 'recent-ad', updates: 0 , class: 'text-blue-500'},
  { icon: 'fas fa-bookmark', title: 'Saved', id: 'saved', updates: 0, class: 'text-purple-700' },
  { icon: 'fas fa-play', title: 'Videos', id: 'videos', updates: 0, class: 'text-green-500' },
  { icon: 'fas fa-sun', title: 'Weather', id: 'weather', updates: 0, class: 'text-orange-500' },
]